====================================================================
1. LOGIN_ID_SEQ   (This is a sequence for the LOGIN USER ID)

	CREATE SEQUENCE LOGIN_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;
====================================================================
2. LOGIN_DETAILS  (This table contains the login credentials of the users)
	
	CREATE TABLE LOGIN_DETAILS (

		USER_ID INTEGER  NOT NULL DEFAULT NEXTVAL('LOGIN_ID_SEQ'),
		USER_NAME VARCHAR(64) NOT NULL,
		PASSWORD VARCHAR(64) NOT NULL,
		DISPLAY_NAME VARCHAR(64),
		USER_ROLE_TYPE VARCHAR(64) NOT NULL,
		CREATED_BY VARCHAR(64) ,
		CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
		LAST_UPDATED_BY VARCHAR(64),
		LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,
		
		PRIMARY KEY (USER_ID),
		UNIQUE(USER_NAME)
	);

====================================================================
3. STANDARD_ID_SEQ (This is a sequence for the STANDARD ID)

CREATE SEQUENCE STANDARD_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE; 
====================================================================
4. CLASS_AVBL_STANDARDS (This table contains the Available standards for the school. For example, 10thclass, 5th class etc)

CREATE TABLE CLASS_AVBL_STANDARDS (

STANDARD_ID INTEGER  NOT NULL DEFAULT NEXTVAL('STANDARD_ID_SEQ'),
STANDARD_NAME VARCHAR(64) NOT NULL,
DESCRIPTION VARCHAR(256),
CREATED_BY VARCHAR(64) ,
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (STANDARD_ID),
UNIQUE(STANDARD_NAME)
);

====================================================================
CREATE SEQUENCE STUDENT_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;

CREATE TABLE STUDENT_DETAILS (

STUDENT_ID INTEGER  NOT NULL DEFAULT NEXTVAL('STUDENT_ID_SEQ'),
STUDENT_FIRST_NAME VARCHAR(64) NOT NULL,
STUDENT_SECOND_NAME VARCHAR(64),
STUDENT_LAST_NAME VARCHAR(64),
DOB VARCHAR(30),
FATHER_NAME  VARCHAR(64),
MOTHER_NAME  VARCHAR(64),
REGISTERED_STANDARD VARCHAR(64) NOT NULL,
REGISTERED_SECTION VARCHAR(64),
ADDRESS  VARCHAR(512),
CREATED_BY VARCHAR(64),
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (STUDENT_ID)
);


-------------------------------------------------------------------