
CREATE SEQUENCE BRANCH_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;

CREATE TABLE SCHOOL_BRANCHES (
BRANCH_ID INTEGER  NOT NULL DEFAULT NEXTVAL('BRANCH_ID_SEQ'),
BRANCH_NAME VARCHAR(64) NOT NULL,
BRANCH_ADDRESS  VARCHAR(512),
CREATED_BY VARCHAR(64) ,
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (BRANCH_ID)
);

INSERT INTO SCHOOL_BRANCHES(BRANCH_ID,BRANCH_NAME,BRANCH_ADDRESS,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE) VALUES(1,'New York','NewYork Downtown','srikanth',current_timestamp,'srikanth',current_timestamp);
INSERT INTO SCHOOL_BRANCHES(BRANCH_ID,BRANCH_NAME,BRANCH_ADDRESS,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE) VALUES(2,'California','California Downtown','srikanth',current_timestamp,'srikanth',current_timestamp);


select * from SCHOOL_BRANCHES;
----------------------------------------------------------

CREATE SEQUENCE STANDARD_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;

CREATE TABLE CLASS_AVBL_STANDARDS (

STANDARD_ID INTEGER  NOT NULL DEFAULT NEXTVAL('STANDARD_ID_SEQ'),
STANDARD_NAME VARCHAR(64) NOT NULL,
BRANCH_ID INTEGER NOT NULL   references SCHOOL_BRANCHES(BRANCH_ID),
DESCRIPTION VARCHAR(256),
CREATED_BY VARCHAR(64) ,
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (STANDARD_ID),
UNIQUE(BRANCH_ID,STANDARD_NAME)
);

select * from CLASS_AVBL_STANDARDS;

--DROP TABLE CLASS_AVBL_STANDARDS;

INSERT INTO CLASS_AVBL_STANDARDS(STANDARD_NAME,BRANCH_ID, DESCRIPTION, CREATED_BY,  LAST_UPDATED_BY) VALUES('1st Standard',1, 'This standard is relavant for 1st class students.','srikanth','srikanth');
INSERT INTO CLASS_AVBL_STANDARDS(STANDARD_NAME,BRANCH_ID, DESCRIPTION, CREATED_BY,  LAST_UPDATED_BY) VALUES('2nd Standard', 1, 'This standard is relavant for 2nd class students.','srikanth','srikanth');
select STANDARD_ID, STANDARD_NAME FROM CLASS_AVBL_STANDARDS;


commit;
-------------------------------------------------------------------
CREATE SEQUENCE SECTION_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;

CREATE TABLE CLASS_AVBL_SECTIONS (

SECTION_ID INTEGER  NOT NULL DEFAULT NEXTVAL('SECTION_ID_SEQ'),
SECTION_NAME VARCHAR(64) NOT NULL,
BRANCH_ID  INTEGER NOT NULL   references SCHOOL_BRANCHES(BRANCH_ID),
STANDARD_ID INTEGER NOT NULL references CLASS_AVBL_STANDARDS(STANDARD_ID),
DESCRIPTION VARCHAR(256),
CREATED_BY VARCHAR(64) ,
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (SECTION_ID),
UNIQUE(STANDARD_ID,SECTION_NAME)
);

commit;

--drop table CLASS_AVBL_SECTIONS;

select * from CLASS_AVBL_SECTIONS;

INSERT INTO CLASS_AVBL_SECTIONS(SECTION_NAME,BRANCH_ID, STANDARD_ID, DESCRIPTION, CREATED_BY,  LAST_UPDATED_BY) VALUES('Section-A',1,10, 'This section is relavant for 1st class students.','srikanth','srikanth');
INSERT INTO CLASS_AVBL_SECTIONS(SECTION_NAME, BRANCH_ID, STANDARD_ID, DESCRIPTION, CREATED_BY,  LAST_UPDATED_BY) VALUES('Section-B',1,10, 'This section is relavant for 2nd class students.','srikanth','srikanth');

INSERT INTO CLASS_AVBL_SECTIONS(SECTION_NAME,BRANCH_ID, STANDARD_ID, DESCRIPTION, CREATED_BY,  LAST_UPDATED_BY) VALUES('Section-C',1,10, 'This section is relavant for 2nd class students.','srikanth','srikanth');
INSERT INTO CLASS_AVBL_SECTIONS(SECTION_NAME, BRANCH_ID,STANDARD_ID, DESCRIPTION, CREATED_BY,  LAST_UPDATED_BY) VALUES('Section-D',1,10, 'This section is relavant for 2nd class students.','srikanth','srikanth');
----------------------------------------------------------

CREATE SEQUENCE STUDENT_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;

CREATE TABLE STUDENT_DETAILS (

STUDENT_ID INTEGER  NOT NULL DEFAULT NEXTVAL('STUDENT_ID_SEQ'),
STUDENT_FIRST_NAME VARCHAR(64) NOT NULL,
STUDENT_SECOND_NAME VARCHAR(64),
STUDENT_LAST_NAME VARCHAR(64),
DOB DATE,
GENDER VARCHAR(2),
FATHER_NAME  VARCHAR(64),
MOTHER_NAME  VARCHAR(64),
BRANCH_ID INTEGER NOT NULL   references SCHOOL_BRANCHES(BRANCH_ID),
REGISTERED_STANDARD INTEGER NOT NULL  references CLASS_AVBL_STANDARDS(STANDARD_ID),
REGISTERED_SECTION INTEGER  NOT NULL  references CLASS_AVBL_SECTIONS(SECTION_ID),
ADDRESS  VARCHAR(512),
EMAIL  VARCHAR(30),
PHONE_NO  VARCHAR(10),
SECONDARY_PHONE_NO  VARCHAR(10),
CREATED_BY VARCHAR(64),
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (STUDENT_ID)
);


INSERT INTO STUDENT_DETAILS(STUDENT_FIRST_NAME,STUDENT_SECOND_NAME,STUDENT_LAST_NAME,DOB,GENDER,FATHER_NAME, MOTHER_NAME,BRANCH_ID,REGISTERED_STANDARD,REGISTERED_SECTION,ADDRESS, EMAIL,
PHONE_NO, SECONDARY_PHONE_NO,CREATED_BY, LAST_UPDATED_BY) 
VALUES ('Srikanth',null,'Ande',Now(),'M','Pavan','Vijaya',1,9,19,'Guntur','srikanthande1990@gmail.com','9052366146',null,'srikanth','srikanth');

select * from STUDENT_DETAILS WHERE REGISTERED_SECTION =23; 

select currval('STUDENT_ID_SEQ') as seq;
--drop table STUDENT_DETAILS;

commit;
-------------------------------------------------------------------
CREATE TABLE LOGIN_DETAILS (

USER_NAME VARCHAR(64) NOT NULL,
PASSWORD VARCHAR(64) NOT NULL,
DISPLAY_NAME VARCHAR(64),
PWD_RESET_FLAG VARCHAR(64),
USER_ROLE_TYPE VARCHAR(64) NOT NULL,
EMAIL  VARCHAR(30),
PHONE_NO  VARCHAR(10),
CREATED_BY VARCHAR(64) ,
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (USER_NAME)
);

drop table LOGIN_DETAILS;

--CREATE SEQUENCE LOGIN_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;

SELECT current_timestamp ;

SELECT * FROM LOGIN_DETAILS;

INSERT INTO LOGIN_DETAILS(USER_NAME, PASSWORD, DISPLAY_NAME,PWD_RESET_FLAG,USER_ROLE_TYPE,CREATED_BY,  LAST_UPDATED_BY) VALUES('srikanth', '5a15878df5a959e8e1f5c28bb6354a0b9722838d', 'Srikanth Ande','Y','Admin','srikanth','srikanth');


UPDATE LOGIN_DETAILS
set display_name = 'Srikanth Ande', last_update_date = current_timestamp
where user_id = 1;

COMMIT;
----------------------------------------------------------

CREATE SEQUENCE TEACHER_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;

CREATE TABLE TEACHER_DETAILS (

TEACHER_ID INTEGER  NOT NULL DEFAULT NEXTVAL('TEACHER_ID_SEQ'),
TEACHER_FIRST_NAME VARCHAR(64) NOT NULL,
TEACHER_SECOND_NAME VARCHAR(64),
TEACHER_LAST_NAME VARCHAR(64),
DOB DATE,
GENDER VARCHAR(2),
ADDRESS  VARCHAR(512),
SPECIALIZATION  VARCHAR(512),
BRANCH_ID INTEGER NOT NULL   references SCHOOL_BRANCHES(BRANCH_ID),
EMAIL  VARCHAR(30),
PHONE_NO  VARCHAR(10),
SECONDARY_PHONE_NO  VARCHAR(10),
CREATED_BY VARCHAR(64),
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (TEACHER_ID)
);

--DROP TABLE TEACHER_DETAILS;

select * from TEACHER_DETAILS;

select * from TEACHER_DETAILS WHERE BRANCH_ID =1;

----------------------------------------------------------------
select * from LOGIN_DETAILS limit 5 offset 3;

SELECT USER_NAME, PASSWORD, DISPLAY_NAME, PWD_RESET_FLAG, USER_ROLE_TYPE, CREATED_BY FROM LOGIN_DETAILS WHERE  CREATED_BY like '%%' order by USER_NAME asc limit 6 OFFSET 5;

SELECT USER_NAME, PASSWORD, DISPLAY_NAME, PWD_RESET_FLAG, USER_ROLE_TYPE, CREATED_BY FROM LOGIN_DETAILS WHERE  CREATED_BY like '%%' order by USER_NAME asc limit 3 OFFSET 0;

SELECT USER_NAME, PASSWORD, DISPLAY_NAME, PWD_RESET_FLAG, USER_ROLE_TYPE, CREATED_BY FROM LOGIN_DETAILS limit 3 OFFSET 1;
select count(*) as range FROM SCHOOL_BRANCHES;

----------------------------------------------------------------
CREATE SEQUENCE SUBJECT_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;

CREATE TABLE SUBJECTS_DETAILS (

SUBJECT_ID INTEGER  NOT NULL DEFAULT NEXTVAL('SUBJECT_ID_SEQ'),
SUBJECT_NAME VARCHAR(64) NOT NULL,
SUBJECT_DESC VARCHAR(256),
SUBJECT_TYPE VARCHAR(16) DEFAULT 'NORMAL',
BRANCH_ID INTEGER NOT NULL   references SCHOOL_BRANCHES(BRANCH_ID),
CREATED_BY VARCHAR(64),
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (SUBJECT_ID),
UNIQUE(BRANCH_ID,SUBJECT_NAME)

);

select * from SUBJECTS_DETAILS order by creation_date desc; WHERE SUBJECT_TYPE <> 'SPECIAL';

select * from SUBJECTS_DETAILS ;

drop table SUBJECTS_DETAILS;

INSERT INTO SUBJECTS_DETAILS(SUBJECT_NAME, SUBJECT_DESC,BRANCH_ID, CREATED_BY,  LAST_UPDATED_BY) VALUES('Sub 3', 'Sub 3',1,'srikanth','srikanth');

commit;
------------------------------------------------------------------------

CREATE SEQUENCE TIME_TABLE_TEMPLATE_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;


CREATE TABLE TIME_TABLE_TEMPLATES (
TIME_TABLE_TEMPLATE_ID INTEGER  NOT NULL DEFAULT NEXTVAL('TIME_TABLE_TEMPLATE_ID_SEQ'),
TEMPLATE_NAME VARCHAR(64) NOT NULL,
NO_OF_SLOTS_USED INTEGER NOT NULL,
SLOT1_FROM TIME,
SLOT1_TO TIME,
SLOT2_FROM TIME,
SLOT2_TO TIME,
SLOT3_FROM TIME,
SLOT3_TO TIME,
SLOT4_FROM TIME,
SLOT4_TO TIME,
SLOT5_FROM TIME,
SLOT5_TO TIME,
SLOT6_FROM TIME,
SLOT6_TO TIME,
SLOT7_FROM TIME,
SLOT7_TO TIME,
SLOT8_FROM TIME,
SLOT8_TO TIME,
SLOT9_FROM TIME,
SLOT9_TO TIME,
SLOT10_FROM TIME,
SLOT10_TO TIME,
SLOT11_FROM TIME,
SLOT11_TO TIME,
SLOT12_FROM TIME,
SLOT12_TO TIME,
SLOT13_FROM TIME,
SLOT13_TO TIME,
SLOT14_FROM TIME,
SLOT14_TO TIME,
SLOT15_FROM TIME,
SLOT15_TO TIME,
SLOT16_FROM TIME,
SLOT16_TO TIME,
SLOT17_FROM TIME,
SLOT17_TO TIME,
SLOT18_FROM TIME,
SLOT18_TO TIME,
SLOT19_FROM TIME,
SLOT19_TO TIME,
SLOT20_FROM TIME,
SLOT20_TO TIME,
SLOT21_FROM TIME,
SLOT21_TO TIME,
SLOT22_FROM TIME,
SLOT22_TO TIME,
SLOT23_FROM TIME,
SLOT23_TO TIME,
SLOT24_FROM TIME,
SLOT24_TO TIME,
CREATED_BY VARCHAR(64),
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (TIME_TABLE_TEMPLATE_ID),
UNIQUE(TEMPLATE_NAME)
);


SELECT * FROM TIME_TABLE_TEMPLATES;




------------------------------------------------------------------------

CREATE SEQUENCE SECTION_SUBJECT_TIME_TABLE_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;


CREATE TABLE SECTION_SUBJECT_TIME_TABLE (
SECTION_SUBJECT_TIME_TABLE_ID INTEGER  NOT NULL DEFAULT NEXTVAL('SECTION_SUBJECT_TIME_TABLE_ID_SEQ'),
TEMPLATE_ID INTEGER  NOT NULL  references TIME_TABLE_TEMPLATES(TIME_TABLE_TEMPLATE_ID),
NO_OF_SLOTS_USED INTEGER NOT NULL,
SECTION_ID INTEGER  NOT NULL  references CLASS_AVBL_SECTIONS(SECTION_ID),
ACTIVE_FLAG VARCHAR(2) DEFAULT 'Y',
DAY_OF_WEEK VARCHAR(32) NOT NULL,
SLOT1 INTEGER,
SLOT2 INTEGER,
SLOT3 INTEGER,
SLOT4 INTEGER,
SLOT5 INTEGER,
SLOT6 INTEGER,
SLOT7 INTEGER,
SLOT8 INTEGER,
SLOT9 INTEGER,
SLOT10 INTEGER,
SLOT11 INTEGER,
SLOT12 INTEGER,
SLOT13 INTEGER,
SLOT14 INTEGER,
SLOT15 INTEGER,
SLOT16 INTEGER,
SLOT17 INTEGER,
SLOT18 INTEGER,
SLOT19 INTEGER,
SLOT20 INTEGER,
SLOT21 INTEGER,
SLOT22 INTEGER,
SLOT23 INTEGER,
SLOT24 INTEGER,
CREATED_BY VARCHAR(64),
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (SECTION_SUBJECT_TIME_TABLE_ID)
);



select * from SUBJECTS_DETAILS where subject_id=56;

select CURRVAL('SECTION_SUBJECT_TIME_TABLE_ID_SEQ');

COMMIT;

------------------------------------------------------------------------

CREATE SEQUENCE TEACHER_SUBJECT_TIME_TABLE_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;



CREATE TABLE TEACHER_SUBJECT_TIME_TABLE (
TEACHER_SUBJECT_TIME_TABLE_ID INTEGER  NOT NULL DEFAULT NEXTVAL('TEACHER_SUBJECT_TIME_TABLE_ID_SEQ'),
TIME_TABLE_TEMPLATE_ID INTEGER  NOT NULL  references TIME_TABLE_TEMPLATES(TIME_TABLE_TEMPLATE_ID),
SECTION_SUBJECT_TIME_TABLE_ID INTEGER  NOT NULL  references SECTION_SUBJECT_TIME_TABLE(SECTION_SUBJECT_TIME_TABLE_ID),
TEACHER_ID INTEGER references TEACHER_DETAILS(TEACHER_ID),
SLOT_NUMBER INTEGER NOT NULL,
CREATED_BY VARCHAR(64),
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (TEACHER_SUBJECT_TIME_TABLE_ID)
);


SELECT * FROM TEACHER_SUBJECT_TIME_TABLE;

--truncate table TEACHER_SUBJECT_TIME_TABLE,SECTION_SUBJECT_TIME_TABLE;


commit;


------------------------------------------------------------------------

CREATE SEQUENCE SCHOOL_HOMEWORK_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;



CREATE TABLE SCHOOL_HOMEWORK (
SCHOOL_HOMEWORK_ID INTEGER  NOT NULL DEFAULT NEXTVAL('SCHOOL_HOMEWORK_ID_SEQ'),
BRANCH_ID INTEGER NOT NULL   references SCHOOL_BRANCHES(BRANCH_ID),
STANDARD_ID INTEGER NOT NULL  references CLASS_AVBL_STANDARDS(STANDARD_ID),
SECTION_ID INTEGER  NOT NULL  references CLASS_AVBL_SECTIONS(SECTION_ID),
ASSIGNMENT_DATE DATE NOT NULL,
SUBJECT_ID INTEGER NOT NULL references SUBJECTS_DETAILS(SUBJECT_ID),
STUDENT_ID INTEGER ,
HOMEWORK_DETAILS TEXT,
CREATED_BY VARCHAR(64),
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (SCHOOL_HOMEWORK_ID)
);

select * from SCHOOL_HOMEWORK;


commit;

------------------------------------------------------------------------
--There should be an entry for each exam, then need the exam schedule w.r.t subject & its timings and then enter the exam scores for each subject

CREATE SEQUENCE SCHOOL_EXAMS_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;

--A school exam entry can't be deleted from the table if the end_date is completed.
CREATE TABLE SCHOOL_EXAMS (
SCHOOL_EXAMS_ID INTEGER  NOT NULL DEFAULT NEXTVAL('SCHOOL_EXAMS_ID_SEQ'),
BRANCH_ID INTEGER NOT NULL   references SCHOOL_BRANCHES(BRANCH_ID),
STANDARD_ID INTEGER NOT NULL  references CLASS_AVBL_STANDARDS(STANDARD_ID),
SECTION_ID INTEGER  NOT NULL  references CLASS_AVBL_SECTIONS(SECTION_ID),
EXAM_START_DATE DATE NOT NULL,
EXAM_END_DATE DATE NOT NULL ,
EXAM_DETAILS TEXT,
CREATED_BY VARCHAR(64),
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (SCHOOL_EXAMS_ID)
);

select * from SCHOOL_EXAMS;

--drop table SCHOOL_EXAMS;

------------------------------------------------------------------------

CREATE SEQUENCE SCHOOL_EXAMS_DETAILS_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;

CREATE TABLE SCHOOL_EXAMS_DETAILS (
SCHOOL_EXAMS_DETAILS_ID INTEGER  NOT NULL DEFAULT NEXTVAL('SCHOOL_EXAMS_DETAILS_ID_SEQ'),
SCHOOL_EXAMS_ID INTEGER NOT NULL   references SCHOOL_EXAMS(SCHOOL_EXAMS_ID),
SUBJECT_ID INTEGER NOT NULL references SUBJECTS_DETAILS(SUBJECT_ID),
SUB_EXAM_DATE  DATE NOT NULL,
SUB_EXAM_START_TIME TIME NOT NULL,
SUB_EXAM_END_TIME TIME NOT NULL,
CREATED_BY VARCHAR(64),
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (SCHOOL_EXAMS_DETAILS_ID)
);

CREATE INDEX SCHOOL_EXAMS_DETAILS_INDEX_EXAM_ID ON SCHOOL_EXAMS_DETAILS (SCHOOL_EXAMS_ID);

select * from SCHOOL_EXAMS_DETAILS;


------------------------------------------------------------------------

CREATE SEQUENCE SCHOOL_EVALUATION_SCORES_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;

CREATE TABLE SCHOOL_EVALUATION_SCORES (
SCHOOL_EVALUATION_SCORES_ID INTEGER  NOT NULL DEFAULT NEXTVAL('SCHOOL_EVALUATION_SCORES_ID_SEQ'),
BRANCH_ID INTEGER NOT NULL   references SCHOOL_BRANCHES(BRANCH_ID),
STANDARD_ID INTEGER NOT NULL  references CLASS_AVBL_STANDARDS(STANDARD_ID),
SECTION_ID INTEGER  NOT NULL  references CLASS_AVBL_SECTIONS(SECTION_ID),
STUDENT_ID INTEGER ,
SCHOOL_EXAMS_ID  INTEGER NOT NULL references SCHOOL_EXAMS(SCHOOL_EXAMS_ID),
CREATED_BY VARCHAR(64),
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (SCHOOL_EVALUATION_SCORES_ID)
);

select * from SCHOOL_EVALUATION_SCORES;

------------------------------------------------------------------------

CREATE SEQUENCE SCHOOL_EVALUATION_SCORES_DETAILS_ID_SEQ INCREMENT BY 1 MINVALUE 1 NO CYCLE;

CREATE TABLE SCHOOL_EVALUATION_SCORES_DETAILS (
SCHOOL_EVALUATION_SCORES_DETAILS_ID INTEGER  NOT NULL DEFAULT NEXTVAL('SCHOOL_EVALUATION_SCORES_DETAILS_ID_SEQ'),
SCHOOL_EVALUATION_SCORES_ID INTEGER NOT NULL   references SCHOOL_EVALUATION_SCORES(SCHOOL_EVALUATION_SCORES_ID),
SUBJECT_ID INTEGER NOT NULL references SUBJECTS_DETAILS(SUBJECT_ID),
SUBJECT_SCORE INTEGER DEFAULT 0,
GRADE VARCHAR(64), --dummy column for now. Not in use
COMMENTS TEXT,
CREATED_BY VARCHAR(64),
CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
LAST_UPDATED_BY VARCHAR(64),
LAST_UPDATE_DATE TIMESTAMP DEFAULT current_timestamp,

PRIMARY KEY (SCHOOL_EVALUATION_SCORES_ID)
);

select * from SCHOOL_EVALUATION_SCORES_DETAILS;

------------------------------------------------------------------------